"""Type stubs for the compiled Rust core (infy_core).

The runtime module is a pyo3 extension with no introspectable signatures, so
these stubs give the Python/Rust boundary real types for mypy.
"""

from typing import Any

def parse_json(text: str) -> Any: ...
def parse_partial_json(text: str) -> Any: ...
def extract_json_from_markdown(text: str) -> Any: ...
def count_tokens(text: str) -> int: ...
def count_tokens_batch(texts: list[str]) -> list[int]: ...
def cosine_similarity(a: list[float], b: list[float]) -> float: ...
def batch_cosine_similarity(
    query: list[float],
    documents: list[list[float]],
    top_k: int | None = ...,
) -> list[tuple[int, float]]: ...
def inner_product(a: list[float], b: list[float]) -> float: ...
def fast_hash(text: str) -> int: ...
def fast_hash_batch(texts: list[str]) -> list[int]: ...
